version: '3.9'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lamda,s3
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"